###
GET http://localhost:3000 HTTP/1.1
content-type: text/html

###
POST http://localhost:3000 HTTP/1.1
content-type: text/html

###
GET http://localhost:3000/api/layers HTTP/1.1
content-type: application/json